name: psp
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.11,<3.13
  - pandas>=2.3.3,<3.0.0
  - numpy>=1.24,<3.0.0
  - scikit-learn>=1.4,<2.0.0
  - requests>=2.32.5,<3.0.0
  - jupyter>=1.1.1,<2.0.0
  - ipykernel>=6.30.1,<7.0.0
  - pytorch>=2.8.0,<3.0.0     
  - pip
  - pip:
      - transformers>=4.56.2,<5.0.0
      - huggingface-hub>=0.35.3,<0.36.0
      - gilda


